---
# Name your file secrets.yml

development:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000
  SESSION_SECRET: HXfC5njTrTnBQq9glyCOzBRnlPERKVaeVNtu1gXMGF-YxAXkfo9A6R_obGuC6jACgqG2Zt_o_fYymS0nUXJ99g==

app_test:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000

test:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000
  SESSION_SECRET: HXfC5njTrTnBQq9glyCOzBRnlPERKVaeVNtu1gXMGF-YxAXkfo9A6R_obGuC6jACgqG2Zt_o_fYymS0nUXJ99g==

production:
  API_HOST: https://tns-api.herokuapp.com/
  APP_HOST: https://tns.herokuapp.com/
  SESSION_SECRET: HXfC5njTrTnBQq9glyCOzBRnlPERKVaeVNtu1gXMGF-YxAXkfo9A6R_obGuC6jACgqG2Zt_o_fYymS0nUXJ99g==